SDK-OSMO = " \
    lksctp-tools-dev \
    libusb1-dev \
    libtalloc-dev \
    libosmocore-dev \
    libosmo-sccp-staticdev \
    libosmo-abis-dev \
    libosmotrau-dev \
    libgtp-dev \
    libdbi-dev \
    libsmpp34-dev \
    gpsd-dev \
    "

SDK-EXTRAS ?= ""
#SDK-EXTRAS_qemux86 ?= " valgrind lttng-ust-dev"
#SDK-EXTRAS_qemux86-64 ?= " lttng-ust-dev"
#SDK-EXTRAS_qemuppc ?= " lttng-ust-dev"
#SDK-EXTRAS_qemuarm ?= " lttng-ust-dev"
